# Generated by Django 6.0 on 2025-12-21 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_students_studentprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
